from .base_frame_editor import BaseFrameEditor
from .base_bbox_plotter import BaseBboxPlotter
from .basic_frame_editors.frame_normlizer import FrameNormalizer
from .basic_frame_editors.frame_info_overlay import FrameInfoOverlay
from .basic_frame_editors.histogram_equalizer import HistogramEqualizer
